AudioOutputDevice=alsa_output.usb-SteelSeries_Arctis_Nova_7-00.analog-stereo
AudioOutputUseDefault=true
AudioVirtualSinkForceMaxValue=true
AutoStartEnabled=true
BenchmarkCacheC0=7.52623e-07;1.93516e-06;5.87232e-06;1.18888e-05;2.42182e-05;4.41929e-05;0.000128987;0.000210487;0.000709512;0.00179056
BenchmarkCacheC1=1.30674e-07;4.13262e-07;9.34379e-07;8.86694e-07;1.83926e-06;4.81508e-06;6.92072e-06;1.89967e-05;3.42521e-05;8.54008e-05
BenchmarkOnBoot=true
ExecutablePath=/app/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAAAAAAAAAAAAArsAAAGtAAAAAAAAAAAAAAK7AAABrQAAAAEAAAAAB4AAAAAAAAAAAAAAArsAAAGt
SetupDone=true
Theme=Breeze
ThemeColors=darkblue
TrayIconMenu=passthrough;menu_preset;separator;show;quit;
