AudioOutputDevice=alsa_output.usb-SteelSeries_Arctis_Nova_7-00.analog-stereo
AudioOutputUseDefault=true
AudioVirtualSinkForceMaxValue=true
AutoStartEnabled=true
BenchmarkCacheC0=4.0021e-07;1.00571e-06;2.01905e-06;4.92589e-06;1.26085e-05;2.64561e-05;5.94696e-05;0.000131756;0.000334199;0.000829917
BenchmarkCacheC1=9.44118e-08;1.87598e-07;3.59092e-07;7.43249e-07;1.46439e-06;2.70736e-06;6.00708e-06;1.124e-05;2.40818e-05;4.81118e-05
BenchmarkOnBoot=true
ExecutablePath=/app/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAATDAAAAGQAAB34AAAHGAAAEwwAAABkAAAd+AAABxgAAAAEAAAAAB4AAAATDAAAAGQAAB34AAAHG
SetupDone=true
Theme=Breeze
ThemeColors=darkblue
TrayIconMenu=passthrough;menu_preset;separator;show;quit;
