flatpak install flathub app.xemu.xemu -y
flatpak install flathub codes.merritt.Nyrna -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub com.calibre_ebook.calibre -y
flatpak install flathub com.discordapp.Discord -y
flatpak install flathub com.feaneron.Boatswain -y
flatpak install flathub com.fightcade.Fightcade -y
flatpak install flathub com.geeks3d.furmark -y
flatpak install flathub com.github.GradienceTeam.Gradience -y
flatpak install flathub com.github.GradienceTeam.Gradience -y
flatpak install flathub com.github.Rosalie241.RMG -y
flatpak install flathub com.github.debauchee.barrier -y
flatpak install flathub com.github.dynobo.normcap -y
flatpak install flathub com.github.hluk.copyq -y
flatpak install flathub com.github.k4zmu2a.spacecadetpinball -y
flatpak install flathub com.github.mtkennerly.ludusavi -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.github.xournalpp.xournalpp -y
flatpak install flathub com.google.Chrome -y
flatpak install flathub com.heroicgameslauncher.hgl -y
flatpak install flathub com.logseq.Logseq -y
flatpak install flathub com.moonlight_stream.Moonlight -y
flatpak install flathub com.obsproject.Studio -y
flatpak install flathub com.quexten.Goldwarden -y
flatpak install rustdesk-origin com.rustdesk.RustDesk -y
flatpak install flathub com.spotify.Client -y
flatpak install flathub com.supermodel3.Supermodel -y
flatpak install flathub com.unity.UnityHub -y
flatpak install flathub com.usebottles.bottles -y
flatpak install flathub com.valvesoftware.SteamLink -y
flatpak install flathub com.visualstudio.code-oss -y
flatpak install flathub com.vivaldi.Vivaldi -y
flatpak install flathub dev.goats.xivlauncher -y
flatpak install flathub dev.vencord.Vesktop -y
flatpak install flathub fr.romainvigier.MetadataCleaner -y
flatpak install flathub io.github.achetagames.epic_asset_manager -y
flatpak install flathub io.github.alainm23.planify -y
flatpak install flathub io.github.antimicrox.antimicrox -y
flatpak install flathub io.github.dosbox-staging -y
flatpak install flathub io.github.dvlv.boxbuddyrs -y
flatpak install flathub io.github.fastrizwaan.WineZGUI -y
flatpak install flathub io.github.flattool.Warehouse -y
flatpak install flathub io.github.hmlendea.geforcenow-electron -y
flatpak install flathub io.github.kotatogram -y
flatpak install flathub io.github.martchus.syncthingtray -y
flatpak install flathub io.github.philipk.boilr -y
flatpak install flathub io.github.prateekmedia.appimagepool -y
flatpak install flathub io.github.seadve.Kooha -y
flatpak install flathub io.github.shiftey.Desktop -y
flatpak install flathub io.github.shiiion.primehack -y
flatpak install flathub io.github.streetpea.Chiaki4deck -y
flatpak install flathub io.github.unknownskl.greenlight -y
flatpak install flathub io.github.vikdevelop.SaveDesktop -y
flatpak install flathub io.github.zyedidia.micro -y
flatpak install flathub io.itch.itch -y
flatpak install flathub it.mijorus.gearlever -y
flatpak install flathub me.timschneeberger.jdsp4linux -y
flatpak install launcher.moe moe.launcher.an-anime-borb-launcher -y
flatpak install launcher.moe moe.launcher.an-anime-game-launcher -y
flatpak install launcher.moe moe.launcher.anime-games-launcher -y
flatpak install launcher.moe moe.launcher.wavey-launcher -y
flatpak install flathub net.cozic.joplin_desktop -y
flatpak install flathub net.davidotek.pupgui2 -y
flatpak install flathub net.kuribo64.melonDS -y
flatpak install flathub net.nokyan.Resources -y
flatpak install flathub net.retrodeck.retrodeck -y
flatpak install flathub net.supertuxkart.SuperTuxKart -y
flatpak install flathub nz.mega.MEGAsync -y
flatpak install flathub org.DolphinEmu.dolphin-emu -y
flatpak install flathub org.audacityteam.Audacity -y
flatpak install flathub org.blender.Blender -y
flatpak install flathub org.duckstation.DuckStation -y
flatpak install flathub org.flycast.Flycast -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub org.kde.elisa -y
flatpak install flathub org.kde.filelight -y
flatpak install flathub org.kde.gwenview -y
flatpak install flathub org.kde.haruna -y
flatpak install flathub org.kde.kcalc -y
flatpak install flathub org.kde.kdenlive -y
flatpak install flathub org.kde.krita -y
flatpak install flathub org.kde.okular -y
flatpak install flathub org.libreoffice.LibreOffice -y
flatpak install flathub org.libretro.RetroArch -y
flatpak install flathub org.mamedev.MAME -y
flatpak install flathub org.mozilla.firefox -y
flatpak install flathub org.ppsspp.PPSSPP -y
flatpak install flathub org.qbittorrent.qBittorrent -y
flatpak install flathub org.remmina.Remmina -y
flatpak install flathub org.scummvm.ScummVM -y
flatpak install flathub org.srb2.SRB2 -y
flatpak install flathub org.srb2.SRB2Kart -y
flatpak install flathub org.supertuxproject.SuperTux -y
flatpak install flathub org.videolan.VLC -y
flatpak install flathub org.x.Warpinator -y
flatpak install flathub page.codeberg.libre_menu_editor.LibreMenuEditor -y
flatpak install flathub sh.ppy.osu -y
flatpak install flathub xyz.tytanium.DoorKnocker -y
