[General]
accentColor=@Variant(\0\0\0\x43\x1\xff\xffggPP\xa4\xa4\0\0)
accentMode=system
networkCacheMaximumMiB=1024
sidebarAutoExpand=true
themeMode=system

[DiscoverView]
filtersJson={}
itemAspectRatio=1
itemSize=160
layoutMode=0
selectedSourceId=wallhaven
wallhaven\Tweak\itemAspectRatio=1
wallhaven\Tweak\itemSize=160
wallhaven\Tweak\layoutMode=0
wallpaper_engine\Tweak\itemAspectRatio=1
wallpaper_engine\Tweak\itemSize=160
wallpaper_engine\Tweak\layoutMode=0

[WallpaperView]
itemAspectRatio=1
itemSize=160
layoutMode=0

[window]
height=1033
width=2538
