### sets my lg tv as the gamescope display
#OUTPUT_CONNECTOR=DP-2
### override gamscopecmd to use custom cursor scale
GAMESCOPECMD="/usr/bin/gamescope --prefer-output DP-2 --xwayland-count 2 --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 --cursor-scale-height 720 --steam"
