---
runtime:
  threads: ~
release:
  check: true
manifest:
  enable: true
language: en-US
theme: dark
roots:
  - store: steam
    path: /var/home/zany130/.local/share/Steam
  - store: heroic
    path: /var/home/zany130/.var/app/com.heroicgameslauncher.hgl/config/heroic
  - store: lutris
    path: /home/zany130/.config/lutris
    database: /home/zany130/.local/share/lutris/pga.db
redirects: []
backup:
  path: /home/zany130/ludusavi-backup
  ignoredGames: []
  filter:
    excludeStoreScreenshots: false
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths:
      - "**/steamtinkerlaunch/**"
      - "**/SK_Res/"
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  retention:
    full: 5
    differential: 10
  format:
    chosen: zip
    zip:
      compression: zstd
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: /home/zany130/ludusavi-backup
  ignoredGames:
    - 8-Bit Bayonetta
    - A Hat in Time
    - "AI: The Somnium Files - nirvanA Initiative"
    - "Anima: Gate of Memories"
    - Attack on Titan 2
    - Clannad
    - Clannad Side Stories
    - Dishonored
    - Dolphin
    - Eden*
    - Edge of Eternity
    - Fable Anniversary
    - Figment
    - "Hellblade: Senua's Sacrifice"
    - Hogwarts Legacy
    - If My Heart Had Wings
    - Jet Set Radio
    - Katamari Damacy Reroll
    - "Kena: Bridge of Spirits"
    - Left 4 Dead 2
    - "Lucid9: Inciting Incident"
    - Mad Father
    - "Memory's Dogma CODE:01"
    - Metro Exodus Enhanced Edition
    - Moss
    - "Naruto Shippuden: Ultimate Ninja Storm 4"
    - "Naruto: Ultimate Ninja Storm"
    - "NieR: Automata"
    - Other EMU saves
    - Pac-Man Museum Plus
    - Persona 3 Reload
    - Ryujinx Saves
    - Shadow of the Tomb Raider
    - Sonic Frontiers
    - "Star Ocean: The Last Hope 4K & Full HD Remaster"
    - "Sunrider: Liberation Day"
    - "Sunrider: Mask of Arcadius"
    - Tales of Arise
    - Tales of Symphonia
    - "The Legend of Heroes: Trails from Zero"
    - "The Legend of Heroes: Trails in the Sky"
    - "The Legend of Heroes: Trails in the Sky SC"
    - "The Legend of Heroes: Trails in the Sky the 3rd"
    - "The Legend of Heroes: Trails into Reverie"
    - "The Legend of Heroes: Trails of Cold Steel"
    - "The Legend of Heroes: Trails of Cold Steel II"
    - "The Legend of Heroes: Trails of Cold Steel III"
    - "The Legend of Heroes: Trails of Cold Steel IV"
    - The Witcher
    - "The Witcher 3: Wild Hunt"
    - The Witness
    - Thief
    - Tomb Raider (2013)
    - Valkyria Chronicles
    - Yooka-Laylee
    - Yuzu Saves
    - "Zanki Zero: Last Beginning"
  toggledPaths:
    Persona 3 Reload:
      /var/home/zany130/.local/share/Steam: false
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  reverseRedirects: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote:
    Custom:
      id: Andres_pCloud
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: /home/linuxbrew/.linuxbrew/bin/rclone
    arguments: "--fast-list --ignore-checksum"
customGames:
  - name: "The Legend of Heroes: Trails of Cold Steel III"
    integration: override
    files:
      - "<home>/Saved Games/Falcom/"
      - "<winLocalAppData>/TrailsOfColdSteel3/ "
      - "<base>/bin/x64/"
    registry: []
  - name: "The Legend of Heroes: Trails of Cold Steel IV"
    integration: override
    files:
      - "<home>/Saved Games/Falcom/"
      - "<winLocalAppData>/TrailsOfColdSteel4/"
      - "<base>/bin/Win64/"
    registry: []
  - name: Ryujinx Saves
    integration: override
    files:
      - ~/.config/Ryujinx/bis/system/save/
      - ~/.config/Ryujinx/bis/user/save/
    registry: []
  - name: Other EMU saves
    integration: override
    files:
      - ~/Emulation/saves
    registry: []
  - name: "The Legend of Heroes: Trails into Reverie"
    integration: override
    files:
      - "<home>/Saved Games/Falcom/"
      - "<winLocalAppData>/Falcom/"
      - "<base>/bin/Win64/"
    registry: []
  - name: Persona 3 Reload
    integration: override
    files:
      - "<winAppData>/SEGA/P3R/Steam/<storeUserId>"
      - "<winLocalAppData>/P3R/Saved/Config/WinGDK"
      - "<winLocalAppData>/P3R/Saved/Config/WindowsNoEditor"
      - "<winLocalAppData>/Packages/SEGAofAmericaInc.L0cb6b3aea_s751p9cej88mt/SystemAppData/wgs/<storeUserId>"
      - "<base>/P3R/Binaries/Win64/"
    registry: []
  - name: "The Legend of Heroes: Trails through Daybreak"
    integration: override
    files:
      - "<home>/Saved Games/Falcom/Kuro"
      - "<winLocalAppData>/Falcom/Kuro"
      - "<base>/reshade-shaders"
      - "<base>/ReShade.ini"
      - "<base>/ReshadeEffectShaderToggler.ini"
      - "<base>/ReShadePreset.ini"
      - "<base>/depth.ini"
      - "<base>/mods"
      - "<base>/dlc"
    registry: []
