[General]
closeToTray=true
networkCookies="@ByteArray(cc=YSo4Uua96MJv4cSPxlOYtAQUPas5Iu0gh0tTnKIoEPFenBLywIk4CvV0b79bWsgj3cM=; HttpOnly; expires=Sat, 18-Apr-2026 02:56:23 GMT; domain=localhost; path=/\n)"
startInTray=true
startupDelay=0
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\0\0\0\0\0\0\fm\0\0\x4\b\0\0\a\x80\0\0\0\0\0\0\fm\0\0\x4\b\0\0\0\0\0\0\0\0\n\0\0\0\a\x80\0\0\0\0\0\0\fm\0\0\x4\b)
zoomFactor=1
