# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: Organize ROMs
    locations:
      - /home/zany130/Games/Dumps/roms
    subfolders: true
    filters:
      - extension:
          - chd
          - iso
          - bin
          - cue
          - gdi
          - n64
          - v64
          - z64
          - smc
          - sfc
          - fig
          - swc
          - a26
          - bin
          - rom
          - gb
          - gbc
          - gba
          - nds
          - cia
          - psp
          - ps1
          - ps2
          - wbfs
          - dol
          - cdi
          - lynx
          - ngp
          - ngc
          - pce
          - sg
          - sms
          - gg
          - tig
          - ws
          - wsc
          # Add more extensions as needed
    actions:
      - python: |
          import os
          import re

          platform_path = os.path.dirname(path)
          platform = os.path.basename(platform_path)

          filename_with_extension = os.path.basename(path)
          filename_without_extension_list = filename_with_extension.rsplit('.', 1)
          filename_without_extension = filename_without_extension_list if isinstance(filename_without_extension_list, list) else filename_without_extension_list

          # Corrected regex to handle optional spaces before and after parentheses/brackets
          game_name = re.sub(r'\s?\(.*?\)\s?|\s?\[.*?\]\s?', '', filename_without_extension).strip()

          return {'platform': platform, 'game_name': game_name}
      - move:
          dest: /var/mnt/emulation/roms/{python.platform}/{python.game_name}/{filename_with_extension}
          on_conflict: skip